// Generated by CoffeeScript 1.6.1
(function() {

  window.svData = [
    {
      x: 1445067,
      y: 7475858,
      attr: {
        date: '2012-06-04',
        type: 'complaint',
        data: {
          c1: true,
          c2: false,
          c3: false
        }
      }
    }, {
      x: 1442443,
      y: 7441135,
      attr: {
        date: '2012-06-04',
        type: 'analysis',
        data: {
          a1: false,
          a2: true
        }
      }
    }, {
      x: 1433729,
      y: 7571251,
      attr: {
        date: '2012-06-04',
        type: 'complaint',
        data: {
          c1: false,
          c2: true,
          c3: true
        }
      }
    }, {
      x: 1485630,
      y: 7487496,
      attr: {
        date: '2012-06-04',
        type: 'analysis',
        data: {
          a1: true,
          a2: false
        }
      }
    }, {
      x: 1485859,
      y: 7486684,
      attr: {
        date: '2012-06-04',
        type: 'complaint',
        data: {
          c1: true,
          c2: true,
          c3: true
        }
      }
    }, {
      x: 1485959,
      y: 7486484,
      attr: {
        date: '2012-06-04',
        type: 'analysis',
        data: {
          a1: false,
          a2: true
        }
      }
    }, {
      x: 1487349,
      y: 7486481,
      attr: {
        date: '2012-06-04',
        type: 'complaint',
        data: {
          c1: true,
          c2: false,
          c3: true
        }
      }
    }, {
      x: 1484559,
      y: 7485398,
      attr: {
        date: '2012-06-04',
        type: 'analysis',
        data: {
          a1: true,
          a2: false
        }
      }
    }, {
      x: 1485477,
      y: 7485262,
      attr: {
        date: '2012-06-04',
        type: 'complaint',
        data: {
          c1: false,
          c2: true,
          c3: false
        }
      }
    }, {
      x: 1480355,
      y: 7484991,
      attr: {
        date: '2012-06-04',
        type: 'complaint',
        data: {
          c1: false,
          c2: false,
          c3: true
        }
      }
    }, {
      x: 1479324,
      y: 7484044,
      attr: {
        date: '2012-06-04',
        type: 'complaint',
        data: {
          c1: true,
          c2: false,
          c3: false
        }
      }
    }, {
      x: 1480470,
      y: 7483705,
      attr: {
        date: '2012-06-04',
        type: 'analysis',
        data: {
          a1: true,
          a2: false
        }
      }
    }, {
      x: 1473782,
      y: 7484653,
      attr: {
        date: '2012-06-04',
        type: 'analysis',
        data: {
          a1: false,
          a2: true
        }
      }
    }, {
      x: 1480000,
      y: 7527337,
      attr: {
        date: '2012-06-06',
        type: 'complaint',
        data: {
          c1: false,
          c2: true,
          c3: true
        }
      }
    }, {
      x: 1455234,
      y: 7534064,
      attr: {
        date: '2012-06-07',
        type: 'complaint',
        data: {
          c1: false,
          c2: true,
          c3: true
        }
      }
    }, {
      x: 1433220,
      y: 7534064,
      attr: {
        date: '2012-06-08',
        type: 'complaint',
        data: {
          c1: false,
          c2: true,
          c3: true
        }
      }
    }
    
  ];

}).call(this);
